
library(tidyverse)
library(foreach)
library(survey)
library(PNSIBGE)
library(doParallel)
library(PNSIBGE)
library(progress)

source("R/supportFunctions.R")
source("R/sampleOrphanhoodHelpers.R") # We use the loadPopnData() function from this file

options(dplyr.summarise.inform = FALSE)



# Load the samples generated by the below function in an easy-to-use format
loadCoresAndParentalOrphanhood = function(mortality="excess") {
  
  uf_lbls = read.csv("data/UF_labels.csv")
  
  df_popn_children = read.csv("data/population/popests_simple_2010_2020.csv") %>%
    filter(age_group %in% paste0(seq(0, 17)), year==2020, !is.na(uf), sex!="both") %>%
    group_by(uf) %>%
    summarise(n_children=sum(n_pop))
  
  df = readRDS(paste0("samples/parentalandcoresorphanhood_", mortality, ".RDS")) %>%
    left_join(df_popn_children, by="uf") %>%
    mutate(orphanhood=p_orphanhood*n_children) %>%
    group_by(uf) %>%
    summarise(mean=mean(orphanhood),
              lower=quantile(orphanhood, 0.025),
              upper=quantile(orphanhood, 0.975)) %>%
    left_join(uf_lbls, by="uf")
  
  return(df)
  
}

#' Generate samples of co-resident orphanhood from PNS 2019 data
sampleCoresAndParentalOrphanhood = function(N=1000,
                                            mortality="excess",
                                            outdir="samples/") {
  
  group_vars = sort(c("uf", "age_group", "sex"))
  
  # Need to load population data and divide by excess deaths
  df_popn = loadPopnDataForOrphanhood(group_vars)
  
  df_popn_children = read.csv("data/population/popests_simple_2010_2020.csv") %>%
    filter(age_group %in% paste0(seq(0, 17)), year==2020, !is.na(uf), sex!="both") %>%
    group_by(uf) %>%
    summarise(n_children=sum(n_pop))
  
  if (mortality == "excess") {
    df_em = readRDS(paste0("samples/excessmortality_", paste0(group_vars, collapse="_"), ".RDS"))
  } else if (mortality == "allcause") {
    df_em = readRDS(paste0("samples/allcausemortality_", paste0(group_vars, collapse="_"), ".RDS"))
  }
  
  # Get maximum ieration counts
  N_em = max(df_em$iter)
  
  # Load and process PNS data
  df_pns_in = readRDS("data/pns2019/pns2019_processed.rds")
  df_pns = df_pns_in %>%
    appendAgeGroups() %>%
    group_by(household_id) %>%
    mutate(n_children_in_house=sum(age <= 17),
           n_adults_in_house = sum((age >= 18) & (age<=59)),
           n_elderly_in_house = sum(age>=60),
           uf = as.numeric(as.character(uf))) %>%
    ungroup()
  
  # df_combinations = expand.grid(uf=unique(df_pns$uf))
  
  # And now we bootstrap
  print("Starting bootstrap...")
  pb = progress_bar$new(format="Bootstrapping co-resident orphanhood... :bar :percent eta: :eta", total=N, clear=FALSE, width=100)
  df_allsamples = foreach(ii = seq(1, N), .combine=rbind, .packages=c("tidyverse", "survey", "foreach", "PNSIBGE")) %dopar% {
    
    # Sample probability that any given older person died
    ii_em = sample(1:N_em, 1)
    df_em_sub = df_em %>% subset(iter==ii_em) %>% select(-iter)
    df_pexcessdeath = df_em_sub %>%
      left_join(df_popn, by=group_vars) %>%
      mutate(p_died=excess_deaths/n_pop) %>%
      select(all_of(c(group_vars, "p_died")))
    
    # Stack this next to the PNS data, sample those that died, and count number of deaths by household
    df_numdeathsbyhousehold = df_pns %>%
      left_join(df_pexcessdeath, by=group_vars) %>%
      ungroup() %>%
      mutate(did_die_elderly = (runif(nrow(df_pns)) < p_died) & (age_group %in% c("60-69", "70+")),
             did_die_parent = (runif(nrow(df_pns)) < p_died) & (age_group %in% c("10-19", "20-29", "30-39", "40-49", "50-59"))) %>%
      group_by(household_id) %>%
      summarise(n_elderly_deaths = sum(did_die_elderly, na.rm=TRUE),
                n_parental_deaths = sum(did_die_parent, na.rm=TRUE),
                n_children = sum(age <= 17),
                uf=uf[1]) %>%
      mutate(n_both = (n_elderly_deaths > 0) * (n_parental_deaths > 0),
             orphanhood=n_both*n_children)
    
    # And now calculate by UF
    df_out = df_numdeathsbyhousehold %>%
      group_by(uf) %>%
      summarise(n_children_in_survey = sum(n_children),
                orphanhood_in_survey = sum(orphanhood),
                p_orphanhood = orphanhood_in_survey/n_children_in_survey) %>%
      mutate(iter = ii)
    
    pb$tick()
    
    return(df_out)
    
  }
  
  # Write files to the /samples/ folder
  fname = paste0(outdir, "parentalandcoresorphanhood_", mortality, ".RDS")
  saveRDS(df_allsamples, fname)

  return(df_allsamples)
  
}

